config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'messages#index'

  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
      @messages = Message.all
  end

  def show
      @message = Message.find(params[:id])
  end

  def new
      @message = Message.new(content:'sample')
  end

  def create
      @message = Message.new(message_params)

    if @message.save
      flash[:success] = 'Message が正常に投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message が投稿されませんでした'
      render :new
    end
  end

  def edit
      @message = Message.find(params[:id])
  end

  def update
  end
  

  def destroy
  end
  
  private

  # Strong Parameter
  def message_params
    params.require(:message).permit(:content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.erb
<h1>id: <%= @message.id %> のメッセージ編集ページ</h1>

<%= form_for(@message) do |f| %>
  <%= f.label :content, 'メッセージ' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<%= link_to '一覧に戻る', messages_path %>

app/views/messages/index.html.erb
<h1>メッセージ一覧</h1>

<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.id, message %> : <%= message.content %></li>
  <% end %>
</ul>

<%= link_to '新規メッセージの投稿', new_message_path %>

app/views/messages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= form_for(@message) do |f| %>
  <%= f.label :content, 'メッセージ' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<%= link_to '一覧に戻る', messages_path %>

app/views/messages/show.html.erb
<h1>id: <%= @message.id %> のメッセージ詳細ページ</h1>

<p><%= @message.content %></p>

<%= link_to '一覧に戻る', messages_path %>
<%= link_to 'このメッセージを編集する', edit_message_path(@message) %>